config/routes.rb
Rails.application.routes.draw do
  
  get "/email/active/:id" , to: 'emails#active', as: :active_email
  get "/email/inactive/:id" , to: 'emails#inactive', as: :inactive_email
  resources :emails

  get "/contacts/:id/unread" , to: 'contacts#unread', as: :unread
  resources :contacts, except: [ 
                                :destroy, :edit, :update 
                              ]

  get "/article_cover/:id" , to: 'articles#image', as: :see_article_cover
  get "/article/unpublish/:id" , to: 'articles#unpublish', as: :unpublish_article
  get "/article/publish/:id" , to: 'articles#publish', as: :publish_article
  resources :articles
  
  get "/categories_cover/:id" , to: 'categories#image', as: :see_category_cover
  resources :categories

  devise_for :users, controllers: { registrations: "users/registrations" }
  get "/author_cover/:id" , to: 'authors#avatar', as: :see_author_avatar
  
  resources :authors, except: [ :new , :create, :destroy ]
  
  resources :params
  
  get "/image_image/:id" , to: 'images#image', as: :see_image_image
  resources :images

  get "/give_articles/just/:num" , to: 'give_articles#just', as: :give_articles_just

  get "/give_articles/bycategory/:id" , to: 'give_articles#by_category', as: :give_articles_by_category
  get "/give_articles/bycategory/:id/just/:num" , to: 'give_articles#by_category_just', as: :give_articles_by_category_just

  get "/give_articles/byauthor/:id" , to: 'give_articles#by_author', as: :give_articles_by_author
  get "/give_articles/byauthor/:id/just/:num" , to: 'give_articles#by_author_just', as: :give_articles_by_author_just

  resources :give_articles, only: [:index, :show, :just, :by_category, :by_category_just, :by_author, :by_author_just]

  get "/give_categories/just/:num" , to: 'give_categories#just', as: :give_categories_just

  resources :give_categories, only: [:index, :show, :just]
  
  
  get "/give_authors/just/:num" , to: 'give_authors#just', as: :give_authors_just

  resources :give_authors, only: [:index, :show, :just]
  
  get "/give_images/just/:num" , to: 'give_images#just', as: :give_images_just

  resources :give_images, only: [:index, :show, :just]
  
  

  root 'backend#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	
  # Relationships
  # has_many :articles_categories, :dependent => :destroy
  # has_many :categories, :through => :articles_categories

  has_and_belongs_to_many :categories
  belongs_to :author

  has_attached_file :cover, styles: { medium: "800x800>", thumb: "300x300>" }
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 20 }
  validates :categories, presence: true
  validates :cover, presence: true
  validates :author_id, presence: true

  # Muestra los registros en orden inverso
  scope :rorder, ->{ order("articles.created_at DESC") }
  # Consulta por id del artículo
  scope :by_id, ->(id){ find(id) }
  
  scope :by_category, ->(id){ includes( :categories ).where('categories.id' => id ) }
  scope :by_author, ->(id){ includes( :author ).where('authors.id' => id ) }
  scope :publicados, ->{ where( state: "published") }
  scope :no_publicados, ->{ where( state: "draft") }

  def cover_thumb
    self.cover.url(:thumb)
  end

  def cover_medium
    self.cover.url(:medium)
  end

  def cover_full
    self.cover.url()
  end

  def all_categories
    self.categories.select("id, name, color")
  end

  def owner
    self.author.as_json( :methods => [ :avatar_thumb ])
  end

  include AASM

  aasm column: "state" do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published 
    end

    event :unpublish do
      transitions from: :published, to: :draft 
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  layout 'seeimages', :only => [ :image ]
  layout "backend", :only => [ :index, :show, :new, :edit, :create, :update, :destroy ]

  before_action :set_article, only: [:show, :edit, :update, :destroy, :image, :unpublish, :publish]
  before_action :set_categories, only: [:edit, :new, :create, :update ]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate( page: params[:page] ).all.rorder
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.author.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /articles/unpublish/:id
  def unpublish
    respond_to do |format|
      if @article.may_unpublish?
        @article.unpublish!
        format.html { redirect_to articles_path, notice: 'Article was successfully marked as draft.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /articles/publish/:id
  def publish
    respond_to do |format|
      if @article.may_publish?
        @article.publish!
        format.html { redirect_to articles_path, notice: 'Article was successfully marked as published.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.by_id(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :cover, category_ids: [])
    end
end

app/views/articles/_form.html.erb
<div class="col-sm-12">
  <%= form_for(@article, html: { class: "form-horizontal" }) do |f| %>
    <% if @article.errors.any? %>
      <div role="alert" class="col-sm-12 alert alert-danger alert-dismissible fade in">
        <button aria-label="Close" data-dismiss="alert" class="close" type="button">
          <span aria-hidden="true">
            ×
          </span>
        </button>
        <p>
          <h3><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
        </p>
        <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :title, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :title, autocomplete: "off", placeholder: "Title", class: "form-control" %>
      </div>  
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :body, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :body, autocomplete: "off", placeholder: "Body", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label "Attach a file", class: "control-label" %>
      </div>
      <div class="col-sm-5" style="padding-left:0">
        <div class="col-sm-12">
          <div class="thumbnail" style="overflow:hidden;">
            <div id="target">
              <%= image_tag @article.cover.url( :thumb ), class: "img-responsive" %>
            </div>
            <br>
            <%= f.file_field :cover, class: "cover" %>
          </div>
        </div>
      </div>
      <div class="col-sm-5" style="padding-left:0">
        <%= f.label "Categories", class: "control-label" %>
        <div class="thumbnail">
          <% @categories.each do |category| -%>
            <div>
              <%= check_box_tag :category_ids, category.id, @article.categories.include?(category), :name => 'article[category_ids][]' -%>
              <%= label_tag :category_ids, category.name -%>
            </div>
          <% end -%>
        </div>
      </div>
    </div>

    <div class="btn-group" role="group" aria-label="Basic example">
      <%= f.button "Save Article &nbsp;<span class=\"glyphicon glyphicon-floppy-disk\"></span>".html_safe, class: "btn btn-primary" %>
  <% end %>
    

app/views/articles/edit.html.erb
	<h1 class="page-header">Editing Article</h1>
	<%= render 'form' %>
	<%= link_to '<span class="glyphicon glyphicon glyphicon-sunglasses"></span>&nbsp;Show'.html_safe, @article, class: "btn btn-info" %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, articles_path, class: "btn btn-danger" %>	
	</div>
</div>

  

app/views/articles/image.html.erb
<div class="row">
	<div class="col-sm-12">
      <%= image_tag @article.cover.url(), class: "img-responsive" %>
	</div>
</div>

app/views/articles/index.html.erb
<% if notice %>
  <div role="alert" class="col-sm-12 alert alert-danger alert-dismissible fade in">
    <button aria-label="Close" data-dismiss="alert" class="close" type="button">
      <span aria-hidden="true">
        ×
      </span>
    </button>
    <p>
      <%= notice %>
    </p>
  </div>
<% end -%>

<h1 class="page-header">Listing Articles</h1>

<h2><%= link_to 'New Article', new_article_path, class: "btn btn-success" %></h2>
<%= will_paginate @articles %>
<table class="table">
  <thead>
    <tr>
      <th class="col-sm-2">Cover</th>
      <th class="col-sm-2">Title</th>
      <th class="col-sm-4">Body</th>
      <th class="col-sm-1 text-center">(Un)Publish</th>
      <th class="col-sm-1 text-center">Show</th>
      <th class="col-sm-1 text-center">Edit</th>
      <th class="col-sm-1 text-center">Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%=link_to( image_tag( article.cover.url( :thumb ), style: "max-width:150px" ), see_article_cover_path(article), :data => { :colorbox => true, :colorbox_height => '100%', :colorbox_width => '100%', :colorbox_iframe => true }) %></td>
        <td><%= article.title %></td>
        <td><%= article.body.truncate(100) %></td>
        <td>
          <% if article.may_unpublish? %>
            <p class="text-center"><%=link_to(  "<span class=\"glyphicon glyphicon-eye-close\"></span>".html_safe , unpublish_article_path(article) ) %></p>
          <% else %>
            <p class="text-center"><%=link_to(  "<span class=\"glyphicon glyphicon-eye-open\"></span>".html_safe , publish_article_path(article) ) %></p>
          <% end %>
        </td>
        <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-sunglasses\"></span>".html_safe, article %></p></td>
        <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, edit_article_path(article) %></p></td>
        <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-trash\"></span>".html_safe, article, id: article.id, method: :delete, data: { confirm: 'Are you sure?' } %></p></td>
      </tr>  
    <% end %>
  </tbody>
</table>
<%= will_paginate @articles %>

app/views/articles/new.html.erb
	<h1 class="page-header">New Article</h1>
  	<%= render 'form' %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, articles_path, class: "btn btn-danger" %>
	</div>
</div>
	

app/views/articles/show.html.erb
<% if notice %>
	<div role="alert" class="col-sm-12 alert alert-success alert-dismissible fade in">
		<button aria-label="Close" data-dismiss="alert" class="close" type="button">
			<span aria-hidden="true">
				×
			</span>
		</button>
		<p>
			<%= notice %>
		</p>
	</div>
<% end -%>
<h1 class="page-header"><%= @article.title %></h1>
<p><%= @article.body %></p> 
<div class="col-sm-12">
	<div class="col-sm-5" style="padding-left:0">
		<div class="col-sm-12">
			<div class="thumbnail" style="overflow:hidden;">
				<div id="target">
					<%= image_tag @article.cover.url( :thumb ), class: "img-responsive" %>
				</div>
			</div>
		</div>	
	</div>
	<div class="col-sm-7">
		<dl class="dl-horizontal">
	      <dt>State</dt>
	      <dd><%= @article.state %></dd>
	      <dt>Visits Count</dt>
	      <dd><%= @article.visits_count %></dd>
	    </dl>
	</div>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
	<%= link_to '<span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit'.html_safe, edit_article_path(@article), class: "btn btn-warning" %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, articles_path, class: "btn btn-danger" %>
</div>