config/routes.rb
Rails.application.routes.draw do
  
  get "/email/active/:id" , to: 'emails#active', as: :active_email
  get "/email/inactive/:id" , to: 'emails#inactive', as: :inactive_email
  resources :emails

  get "/contacts/:id/unread" , to: 'contacts#unread', as: :unread
  resources :contacts, except: [ 
                                :destroy, :edit, :update 
                              ]

  get "/article_cover/:id" , to: 'articles#image', as: :see_article_cover
  get "/article/unpublish/:id" , to: 'articles#unpublish', as: :unpublish_article
  get "/article/publish/:id" , to: 'articles#publish', as: :publish_article
  resources :articles
  
  get "/categories_cover/:id" , to: 'categories#image', as: :see_category_cover
  resources :categories

  devise_for :users, controllers: { registrations: "users/registrations" }
  get "/author_cover/:id" , to: 'authors#avatar', as: :see_author_avatar
  
  resources :authors, except: [ :new , :create, :destroy ]
  
  resources :params
  
  get "/image_image/:id" , to: 'images#image', as: :see_image_image
  resources :images

  get "/give_articles/just/:num" , to: 'give_articles#just', as: :give_articles_just

  get "/give_articles/bycategory/:id" , to: 'give_articles#by_category', as: :give_articles_by_category
  get "/give_articles/bycategory/:id/just/:num" , to: 'give_articles#by_category_just', as: :give_articles_by_category_just

  get "/give_articles/byauthor/:id" , to: 'give_articles#by_author', as: :give_articles_by_author
  get "/give_articles/byauthor/:id/just/:num" , to: 'give_articles#by_author_just', as: :give_articles_by_author_just

  resources :give_articles, only: [:index, :show, :just, :by_category, :by_category_just, :by_author, :by_author_just]

  get "/give_categories/just/:num" , to: 'give_categories#just', as: :give_categories_just

  resources :give_categories, only: [:index, :show, :just]
  
  
  get "/give_authors/just/:num" , to: 'give_authors#just', as: :give_authors_just

  resources :give_authors, only: [:index, :show, :just]
  
  get "/give_images/just/:num" , to: 'give_images#just', as: :give_images_just

  resources :give_images, only: [:index, :show, :just]
  
  

  root 'backend#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :user
  has_many :articles, dependent: :destroy

  has_attached_file :avatar, styles: { medium: "800x800>", thumb: "300x300>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :fullname, length: { minimum: 4 }
  validates :twitter, length: { minimum: 3 }
  validates_format_of :facebook, :with => URI::regexp(%w(http https))
  validates_format_of :website, :with => URI::regexp(%w(http https))
  validates :resume, length: { minimum: 4 }
  validates :user_id, presence: true

  scope :rorder, ->{ order("authors.created_at DESC") }
  scope :by_id, ->(id){ find(id) }
   
  def avatar_thumb
    self.avatar.url( :thumb )
  end
  
  def avatar_medium
    self.avatar.url( :medium )
  end
  
  def avatar_full
    self.avatar.url()
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  layout 'seeimages', :only => [ :avatar ]
  layout "backend", :only => [ :index, :show, :edit, :create, :update, :destroy ]

  before_action :authenticate_user!
  before_action :set_author, only: [:show, :edit, :update, :avatar]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.paginate( page: params[:page] ).all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/1/edit
  def edit
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def avatar    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:fullname, :twitter, :facebook, :website, :resume, :avatar)
    end
end

app/views/authors/_form.html.erb
<div class="col-sm-12">  
  <%= form_for(@author, html: { class: "form-horizontal" }) do |f| %>
    <% if @author.errors.any? %>
      <div role="alert" class="col-sm-12 alert alert-danger alert-dismissible fade in">
        <button aria-label="Close" data-dismiss="alert" class="close" type="button">
          <span aria-hidden="true">
            ×
          </span>
        </button>
        <p>
          <h3><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h3>
        </p>
        <ul>
          <% @author.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h3><%= @author.user.email %></h3>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label "Avatar", class: "control-label" %>
      </div>
      <div class="col-sm-4" style="padding-left:0">
        <div class="col-sm-12">
          <div class="thumbnail" style="overflow:hidden;">
            <div id="target">
              <%= image_tag @author.avatar.url( :thumb ), class: "img-responsive" %>
            </div>
            <br>
            <%= f.file_field :avatar, class: "avatar" %>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :fullname, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :fullname, autocomplete: "off", placeholder: "Full name", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :twitter, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :twitter, autocomplete: "off", placeholder: "Twitter account", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :facebook, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :facebook, autocomplete: "off", placeholder: "Facebook account", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :website, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :website, autocomplete: "off", placeholder: "Website", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :resume, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :resume, autocomplete: "off", placeholder: "Resume", class: "form-control" %>
      </div>
    </div>
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= f.button "Save Author &nbsp;<span class=\"glyphicon glyphicon-floppy-disk\"></span>".html_safe, class: "btn btn-primary" %>
  <% end %>

app/views/authors/avatar.html.erb
<div class="row">
	<div class="col-sm-12">
      <%= image_tag @author.avatar.url(), class: "img-responsive" %>
	</div>
</div>

app/views/authors/edit.html.erb
	<% unless current_user.author.id == @author.id %>
		
		<h1 class="page-header">Editing Author</h1>
		
		<% else %>
		
		<h1 class="page-header">Editing My Profile</h1>	

	<% end %>


	<%= render 'form' %>

	<%= link_to '<span class="glyphicon glyphicon glyphicon-sunglasses"></span>&nbsp;Show'.html_safe, @author, class: "btn btn-info" %>

		<% unless current_user.author.id == @author.id %>

			<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, authors_path, class: "btn btn-danger" %>
			
		<% end %>
	</div>
</div>

app/views/authors/index.html.erb
<% if notice %>
  <div role="alert" class="col-sm-12 alert alert-danger alert-dismissible fade in">
    <button aria-label="Close" data-dismiss="alert" class="close" type="button">
      <span aria-hidden="true">
        ×
      </span>
    </button>
    <p>
      <%= notice %>
    </p>
  </div>
<% end -%>

<h1 class="page-header">Listing Authors</h1>
<%= will_paginate @articles %>
<table class="table">
  <thead>
    <tr>
      <th class="col-sm-2">Avatar</th>
      <th class="col-sm-2">Fullname</th>
      <th class="col-sm-2">Twitter</th>
      <th class="col-sm-4">User</th>
      <th class="col-sm-1 text-center">Show</th>
      <th class="col-sm-1 text-center">Edit</th>          
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><div class="thumbnail" style="overflow:hidden;"><%=link_to( image_tag( author.avatar.url( :thumb ), style: "max-width:150px" ), see_author_avatar_path(author), :data => { :colorbox => true, :colorbox_height => '100%', :colorbox_width => '100%', :colorbox_iframe => true }) %></div></td>
        <td><%= author.fullname %></td>
        <td><%= author.twitter %></td>
        <td><%= author.user.email %></td>
        <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-sunglasses\"></span>".html_safe, author %></p></td>
        <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, edit_author_path(author) %></p></td>
        <!-- <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @articles %>

app/views/authors/new.html.erb
	<h1 class="page-header">New Author</h1>
	<%= render 'form' %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, authors_path, class: "btn btn-danger" %>
	</div>
</div>

app/views/authors/show.html.erb
<% if notice %>
  <div role="alert" class="col-sm-12 alert alert-success alert-dismissible fade in">
    <button aria-label="Close" data-dismiss="alert" class="close" type="button">
      <span aria-hidden="true">
        ×
      </span>
    </button>
    <p>
      <%= notice %>
    </p>
  </div>
<% end -%>
<h1 class="page-header"><%= @author.user.email %></h1>
<div class="col-sm-12">
  <div class="col-sm-4" style="padding-left:0">
    <div class="col-sm-12">
      <div class="thumbnail" style="overflow:hidden;">
        <div id="target">
          <%= image_tag @author.avatar.url( :thumb ), class: "img-responsive" %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="dl-horizontal">
      <dl>
        <dt>Full name:</dt>
        <dd><%= @author.fullname %></dd>
        <dt>Twitter:</dt>
        <dd><%= @author.twitter %></dd>
        <dt>Facebook:</dt>
        <dd><%= @author.facebook %></dd>
        <dt>Website:</dt>
        <dd><%= @author.website %></dd>
        <dt>Resume:</dt>
        <dd><%= @author.resume %></dd>
        <dt>User:</dt>
        <dd><%= @author.user.email %></dd>
      </dl>
    </div> 
  </div>
</div>
  
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to '<span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit'.html_safe, edit_author_path(@author), class: "btn btn-warning" %>

  <% unless current_user.author.id == @author.id %>
    <%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, authors_path, class: "btn btn-danger" %>
  <% end %>
</div>