config/routes.rb
Rails.application.routes.draw do
  
  get "/email/active/:id" , to: 'emails#active', as: :active_email
  get "/email/inactive/:id" , to: 'emails#inactive', as: :inactive_email
  resources :emails

  get "/contacts/:id/unread" , to: 'contacts#unread', as: :unread
  resources :contacts, except: [ 
                                :destroy, :edit, :update 
                              ]

  get "/article_cover/:id" , to: 'articles#image', as: :see_article_cover
  get "/article/unpublish/:id" , to: 'articles#unpublish', as: :unpublish_article
  get "/article/publish/:id" , to: 'articles#publish', as: :publish_article
  resources :articles
  
  get "/categories_cover/:id" , to: 'categories#image', as: :see_category_cover
  resources :categories

  devise_for :users, controllers: { registrations: "users/registrations" }
  get "/author_cover/:id" , to: 'authors#avatar', as: :see_author_avatar
  
  resources :authors, except: [ :new , :create, :destroy ]
  
  resources :params
  
  get "/image_image/:id" , to: 'images#image', as: :see_image_image
  resources :images

  get "/give_articles/just/:num" , to: 'give_articles#just', as: :give_articles_just

  get "/give_articles/bycategory/:id" , to: 'give_articles#by_category', as: :give_articles_by_category
  get "/give_articles/bycategory/:id/just/:num" , to: 'give_articles#by_category_just', as: :give_articles_by_category_just

  get "/give_articles/byauthor/:id" , to: 'give_articles#by_author', as: :give_articles_by_author
  get "/give_articles/byauthor/:id/just/:num" , to: 'give_articles#by_author_just', as: :give_articles_by_author_just

  resources :give_articles, only: [:index, :show, :just, :by_category, :by_category_just, :by_author, :by_author_just]

  get "/give_categories/just/:num" , to: 'give_categories#just', as: :give_categories_just

  resources :give_categories, only: [:index, :show, :just]
  
  
  get "/give_authors/just/:num" , to: 'give_authors#just', as: :give_authors_just

  resources :give_authors, only: [:index, :show, :just]
  
  get "/give_images/just/:num" , to: 'give_images#just', as: :give_images_just

  resources :give_images, only: [:index, :show, :just]
  
  

  root 'backend#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

	# Relationships
	# has_many :articles_categories, :dependent => :destroy
	# has_many :articles, :through => :articles_categories
	has_and_belongs_to_many :articles

	has_attached_file :cover, styles: { medium: "800x800>", thumb: "300x300>" }
	validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 20 }
    validates :color, presence: true
    validates :cover, presence: true
    validates :icon, presence: true, length: { maximum: 1 }

    scope :rorder, ->{ order("categories.created_at DESC") }
  	
  	def cover_thumb
		self.cover.url(:thumb)
	end

	def cover_medium
		self.cover.url(:medium)
	end

	def cover_full
		self.cover.url()
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  layout 'seeimages', :only => [ :image ]
  layout "backend", :only => [ :index, :show, :new, :edit, :create, :update, :destroy ]

  before_action :set_category, only: [:show, :edit, :update, :destroy, :image]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate( page: params[:page] ).all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :color, :cover, :icon)
    end
end

app/views/categories/_form.html.erb
<div class="col-sm-12">  
  <%= form_for(@category, html: { class: "form-horizontal" }) do |f| %>
    <% if @category.errors.any? %>
      <div role="alert" class="col-sm-12 alert alert-danger alert-dismissible fade in">
        <button aria-label="Close" data-dismiss="alert" class="close" type="button">
          <span aria-hidden="true">
            ×
          </span>
        </button>
        <p>
          <h3><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
        </p>
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :name, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :name, autocomplete: "off", placeholder: "Name", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :description, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :description, autocomplete: "off", placeholder: "Description", class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label "Attach a file", class: "control-label" %>
      </div>
      <div class="col-sm-5" style="padding-left:0">
        <div class="col-sm-12">
          <div class="thumbnail" style="overflow:hidden;">
            <div id="target">
              <%= image_tag @category.cover.url( :thumb ), class: "img-responsive" %>
            </div>
            <br>
            <%= f.file_field :cover, class: "cover" %>
          </div>
        </div>
      </div>
      <div class="col-sm-5" style="padding-left:0">
        <%= f.label :color, class: "control-label" %>
        <div class="input-group color">
          <%= f.text_field :color, autocomplete: "off", placeholder: "Color", class: "form-control", readonly: "on" %>
          <span class="input-group-addon"><i></i></span>
        </div>
      </div>
      <div class="col-sm-1" style="padding-left:0">
          <%= f.label :icon, class: "control-label" %>
          <%= f.text_field :icon, autocomplete: "off", placeholder: "Icon", class: "form-control" %>
      </div>

    </div>

    <div class="btn-group" role="group" aria-label="Basic example">
      <%= f.button "Save Category &nbsp;<span class=\"glyphicon glyphicon-floppy-disk\"></span>".html_safe, class: "btn btn-primary" %>
  <% end %>

app/views/categories/edit.html.erb
	<h1 class="page-header">Editing Category</h1>
	<%= render 'form' %>
	<%= link_to '<span class="glyphicon glyphicon glyphicon-sunglasses"></span>&nbsp;Show'.html_safe, @category, class: "btn btn-info" %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, categories_path, class: "btn btn-danger" %>
	</div>
</div>

app/views/categories/image.html.erb
<div class="row">
	<div class="col-sm-12">
      <%= image_tag @category.cover.url(), class: "img-responsive" %>
	</div>
</div>

app/views/categories/index.html.erb
<% if notice %>
  <div role="alert" class="col-sm-12 alert alert-danger alert-dismissible fade in">
    <button aria-label="Close" data-dismiss="alert" class="close" type="button">
      <span aria-hidden="true">
        ×
      </span>
    </button>
    <p>
      <%= notice %>
    </p>
  </div>
<% end -%>

<h1 class="page-header">Listing Categories</h1>
<%= link_to 'New Category', new_category_path, class: "btn btn-success" %>
<%= will_paginate @articles %>
  <table class="table">
    <thead>
      <tr>
        <th class="col-sm-2">Cover</th>
        <th class="col-sm-2">Name</th>
        <th class="col-sm-3">Description</th>
        <th class="col-sm-1 text-center">Icon</th>
        <th class="col-sm-1">Color</th>
        <th class="col-sm-1 text-center">Show</th>
        <th class="col-sm-1 text-center">Edit</th>
        <th class="col-sm-1 text-center">Destroy</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%=link_to( image_tag( category.cover.url( :thumb ), style: "max-width:150px" ), see_category_cover_path(category), :data => { :colorbox => true, :colorbox_height => '100%', :colorbox_width => '100%', :colorbox_iframe => true }) %></td>
          <td><%= category.name %></td>
          <td><%= category.description %></td>
          <td><p class="text-center"><%= category.icon %></p></td>
          <td><div style="width:20px;height:20px;background-color:<%= category.color %>"></div></td>
          <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-sunglasses\"></span>".html_safe, category %></p></td>
          <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, edit_category_path(category) %></p></td>
          <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-trash\"></span>".html_safe, category, id: category.id, method: :delete, data: { confirm: 'Are you sure?' } %></p></td>
        </tr>  
      <% end %>
    </tbody>
  </table>
<%= will_paginate @articles %>

app/views/categories/new.html.erb
	<h1 class="page-header">New Category</h1>
	<%= render 'form' %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, categories_path, class: "btn btn-danger" %>
	</div>
</div>
		

app/views/categories/show.html.erb
<% if notice %>
	<div role="alert" class="col-sm-12 alert alert-success alert-dismissible fade in">
		<button aria-label="Close" data-dismiss="alert" class="close" type="button">
			<span aria-hidden="true">
				×
			</span>
		</button>
		<p>
			<%= notice %>
		</p>
	</div>
<% end -%>
<h1 class="page-header"><%= @category.name %></h1>
<p><%= @category.description %></p>
<div class="col-sm-12">
	<div class="col-sm-5" style="padding-left:0">
	    <div class="col-sm-12">
	      <div class="thumbnail" style="overflow:hidden;">
	        <div id="target">
	        	<%= image_tag @category.cover.url( :thumb ), class: "img-responsive" %>
	        </div>
	      </div>
	    </div>
	</div>
	<div class="col-sm-7">
		<dl>
	      <dt>Color Category</dt>
	      <dd><div style="width:20px;height:20px;background-color:<%= @category.color %>"></div></dd>
	      <dt>Icon</dt>
	      <dd><%= @category.icon %></dd>
	    </dl>
	</div>
</div>

<div class="btn-group" role="group" aria-label="Basic example">
	<%= link_to '<span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit'.html_safe, edit_category_path(@category), class: "btn btn-warning" %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, categories_path, class: "btn btn-danger" %>
</div>