config/routes.rb
Rails.application.routes.draw do
  
  get "/email/active/:id" , to: 'emails#active', as: :active_email
  get "/email/inactive/:id" , to: 'emails#inactive', as: :inactive_email
  resources :emails

  get "/contacts/:id/unread" , to: 'contacts#unread', as: :unread
  resources :contacts, except: [ 
                                :destroy, :edit, :update 
                              ]

  get "/article_cover/:id" , to: 'articles#image', as: :see_article_cover
  get "/article/unpublish/:id" , to: 'articles#unpublish', as: :unpublish_article
  get "/article/publish/:id" , to: 'articles#publish', as: :publish_article
  resources :articles
  
  get "/categories_cover/:id" , to: 'categories#image', as: :see_category_cover
  resources :categories

  devise_for :users, controllers: { registrations: "users/registrations" }
  get "/author_cover/:id" , to: 'authors#avatar', as: :see_author_avatar
  
  resources :authors, except: [ :new , :create, :destroy ]
  
  resources :params
  
  get "/image_image/:id" , to: 'images#image', as: :see_image_image
  resources :images

  get "/give_articles/just/:num" , to: 'give_articles#just', as: :give_articles_just

  get "/give_articles/bycategory/:id" , to: 'give_articles#by_category', as: :give_articles_by_category
  get "/give_articles/bycategory/:id/just/:num" , to: 'give_articles#by_category_just', as: :give_articles_by_category_just

  get "/give_articles/byauthor/:id" , to: 'give_articles#by_author', as: :give_articles_by_author
  get "/give_articles/byauthor/:id/just/:num" , to: 'give_articles#by_author_just', as: :give_articles_by_author_just

  resources :give_articles, only: [:index, :show, :just, :by_category, :by_category_just, :by_author, :by_author_just]

  get "/give_categories/just/:num" , to: 'give_categories#just', as: :give_categories_just

  resources :give_categories, only: [:index, :show, :just]
  
  
  get "/give_authors/just/:num" , to: 'give_authors#just', as: :give_authors_just

  resources :give_authors, only: [:index, :show, :just]
  
  get "/give_images/just/:num" , to: 'give_images#just', as: :give_images_just

  resources :give_images, only: [:index, :show, :just]
  
  

  root 'backend#index'

end

app/models/image.rb
class Image < ActiveRecord::Base

	has_attached_file :image, styles: { medium: "800x800>", thumb: "500x500>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :title, presence: true
    validates :description, presence: true, length: { minimum: 20 }
    validates :image, presence: true
	
	scope :rorder, ->{ order("images.created_at DESC") }
  	
  	def image_thumb
		self.image.url(:thumb)
	end

	def image_medium
		self.image.url(:medium)
	end

	def image_full
		self.image.url()
	end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  layout 'seeimages', :only => [ :image ]
  layout "backend", :only => [ :index, :show, :new, :edit, :create, :update, :destroy ]

  before_action :set_image, only: [:show, :edit, :update, :destroy, :image]

  # GET /images
  # GET /images.json
  def index
    @images = Image.paginate( page: params[:page] ).all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :description, :image)
    end
end

app/views/images/_form.html.erb
<div class="col-sm-12">
  <%= form_for(@image, html: { class: "form-horizontal" }) do |f| %>
    <% if @image.errors.any? %>
      <div role="alert" class="col-sm-12 alert alert-danger alert-dismissible fade in">
        <button aria-label="Close" data-dismiss="alert" class="close" type="button">
          <span aria-hidden="true">
            ×
          </span>
        </button>
        <p>
          <h3><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h3>
        </p>
        <ul>
          <% @image.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :title, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :title, autocomplete: "off", placeholder: "Title", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :description, class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :description, autocomplete: "off", placeholder: "Description", class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label "Attach a file", class: "control-label" %>
      </div>
      <div class="col-sm-5" style="padding-left:0">
        <div class="col-sm-12">
          <div class="thumbnail" style="overflow:hidden;">
            <div id="target">
              <%= image_tag @image.image.url( :thumb ), class: "img-responsive" %>
            </div>
            <br>
            <%= f.file_field :image, class: "image" %>
          </div>
        </div>
      </div>
    </div>
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= f.button "Save Image &nbsp;<span class=\"glyphicon glyphicon-floppy-disk\"></span>".html_safe, class: "btn btn-primary" %>
  <% end %>

app/views/images/edit.html.erb
	<h1 class="page-header">Editing Image</h1>
	<%= render 'form' %>
	<%= link_to '<span class="glyphicon glyphicon glyphicon-sunglasses"></span>&nbsp;Show'.html_safe, @image, class: "btn btn-info" %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, images_path, class: "btn btn-danger" %>
	</div>
</div>

app/views/images/image.html.erb
<div class="row">
	<div class="col-sm-12">
      <%= image_tag @image.image.url(), class: "img-responsive" %>
	</div>
</div>

app/views/images/index.html.erb
<% if notice %>
  <div role="alert" class="col-sm-12 alert alert-danger alert-dismissible fade in">
    <button aria-label="Close" data-dismiss="alert" class="close" type="button">
      <span aria-hidden="true">
        ×
      </span>
    </button>
    <p>
      <%= notice %>
    </p>
  </div>
<% end -%>
<h1 class="page-header">Listing Images</h1>
<%= link_to 'New Image', new_image_path, class: "btn btn-success" %>
<%= will_paginate @articles %>
<table class="table">
  <thead>
    <tr>
      <th class="col-sm-2">Image</th>
      <th class="col-sm-3">Title</th>
      <th class="col-sm-4">Description</th>
      <th class="col-sm-1 text-center">Show</th>
      <th class="col-sm-1 text-center">Edit</th>
      <th class="col-sm-1 text-center">Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%=link_to( image_tag( image.image.url( :thumb ), style: "max-width:150px" ), see_image_image_path(image), :data => { :colorbox => true, :colorbox_height => '100%', :colorbox_width => '100%', :colorbox_iframe => true }) %></td>
        <td><%= image.title %></td>
        <td><%= image.description.truncate(100) %></td>
        <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-sunglasses\"></span>".html_safe, image %></p></td>
        <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, edit_image_path(image) %></p></td>
        <td><p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-trash\"></span>".html_safe, image, method: :delete, data: { confirm: 'Are you sure?' } %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @articles %>

app/views/images/new.html.erb
	<h1 class="page-header">New Image</h1>
	<%= render 'form' %>
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, images_path, class: "btn btn-danger" %>
	</div>
</div>

app/views/images/show.html.erb
<% if notice %>
	<div role="alert" class="col-sm-12 alert alert-success alert-dismissible fade in">
		<button aria-label="Close" data-dismiss="alert" class="close" type="button">
			<span aria-hidden="true">
				×
			</span>
		</button>
		<p>
			<%= notice %>
		</p>
	</div>
<% end -%>
<h1 class="page-header"><%= @image.title %></h1>
<p><%= @image.description %></p>
<div class="col-sm-12">	
	<p>
	<div class="col-sm-5" style="padding-left:0">
		<div class="col-sm-12">
		  <div class="thumbnail" style="overflow:hidden;">
		    <div id="target">
		      <%= image_tag @image.image.url( :thumb ), class: "img-responsive" %>
		    </div>
		  </div>
		</div>
	</div>
	</p>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
	<%= link_to '<span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit'.html_safe, edit_image_path(@image), class: "btn btn-warning" %> 
	<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Back'.html_safe, images_path, class: "btn btn-danger" %>
</div>